OBJS = \
    cont.o \
    abi.o \
    base64.o \
    cbuf.o \
    cont_util.o \
    core_esp8266_app_entry_noextra4k.o \
    core_esp8266_eboot_command.o \
    core_esp8266_flash_utils.o \
    core_esp8266_i2s.o \
    core_esp8266_main.o \
    core_esp8266_noniso.o \
    core_esp8266_phy.o \
    core_esp8266_postmortem.o \
    core_esp8266_si2c.o \
    core_esp8266_sigma_delta.o \
    core_esp8266_timer.o \
    core_esp8266_waveform.o \
    core_esp8266_wiring_analog.o \
    core_esp8266_wiring_digital.o \
    core_esp8266_wiring_pulse.o \
    core_esp8266_wiring_pwm.o \
    core_esp8266_wiring_shift.o \
    core_esp8266_wiring.o \
    debug.o \
    Esp-frag.o \
    Esp-version.o \
    Esp.o \
    FS.o \
    FunctionalInterrupt.o \
    gdb_hooks.o \
    HardwareSerial.o \
    heap.o \
    IPAddress.o \
    cdecode.o \
    cencode.o \
    libc_replacements.o \
    MD5Builder.o \
    Print.o \
    Schedule.o \
    ScheduledFunctions.o \
    sntp-lwip2.o \
    spiffs_api.o \
    spiffs_hal.o \
    spiffs_cache.o \
    spiffs_check.o \
    spiffs_gc.o \
    spiffs_hydrogen.o \
    spiffs_nucleus.o \
    sqrt32.o \
    StackThunk.o \
    Stream.o \
    StreamString.o \
    time.o \
    Tone.o \
    uart.o \
    umm_malloc.o \
    Updater.o \
    WMath.o \
    WString.o
